"""empty message

Revision ID: 4ece70af2bc7
Revises: None
Create Date: 2015-06-15 21:22:54.689758

"""

# revision identifiers, used by Alembic.
revision = '4ece70af2bc7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary',
    sa.Column('idw', sa.Integer(), nullable=False),
    sa.Column('word', sa.Unicode(length=100), nullable=True),
    sa.Column('translation', sa.Unicode(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('idw')
    )
    op.create_index(op.f('ix_vocabulary_translation'), 'vocabulary', ['translation'], unique=False)
    op.create_index(op.f('ix_vocabulary_word'), 'vocabulary', ['word'], unique=True)
    op.create_table('users',
    sa.Column('idu', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=50), nullable=True),
    sa.Column('password_hash', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('idu')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_vocabulary_word'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_translation'), table_name='vocabulary')
    op.drop_table('vocabulary')
    ### end Alembic commands ###
